import { ONE_CONSTANT } from "@domain/constant";

export const BOX_CONSTANT: Readonly<{
	ASCII_BOTTOM_LEFT: string;
	ASCII_BOTTOM_RIGHT: string;
	ASCII_HORIZONTAL: string;
	ASCII_SEPARATOR_LEFT: string;
	ASCII_SEPARATOR_RIGHT: string;
	ASCII_TOP_LEFT: string;
	ASCII_TOP_RIGHT: string;
	ASCII_VERTICAL: string;
	DOUBLE_SIDE_PADDING: number;
	UNICODE_BOTTOM_LEFT: string;
	UNICODE_BOTTOM_RIGHT: string;
	UNICODE_HORIZONTAL: string;
	UNICODE_SEPARATOR_LEFT: string;
	UNICODE_SEPARATOR_RIGHT: string;
	UNICODE_TOP_LEFT: string;
	UNICODE_TOP_RIGHT: string;
	UNICODE_VERTICAL: string;
}> = {
	ASCII_BOTTOM_LEFT: "+",
	ASCII_BOTTOM_RIGHT: "+",
	ASCII_HORIZONTAL: "-",
	ASCII_SEPARATOR_LEFT: "+",
	ASCII_SEPARATOR_RIGHT: "+",
	ASCII_TOP_LEFT: "+",
	ASCII_TOP_RIGHT: "+",
	ASCII_VERTICAL: "|",
	DOUBLE_SIDE_PADDING: ONE_CONSTANT + ONE_CONSTANT,
	UNICODE_BOTTOM_LEFT: "└",
	UNICODE_BOTTOM_RIGHT: "┘",
	UNICODE_HORIZONTAL: "─",
	UNICODE_SEPARATOR_LEFT: "├",
	UNICODE_SEPARATOR_RIGHT: "┤",
	UNICODE_TOP_LEFT: "┌",
	UNICODE_TOP_RIGHT: "┐",
	UNICODE_VERTICAL: "│",
} as const;
